name: UAT deployment
on:
  push:
    branches: ['dev']

jobs:
  build-and-deploy:
     uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment-advanced.yml@main

     secrets:
       secretBuildArgs: |
         SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
         GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
     with:
       namespace: "solarswap-dev"
       ingressEnabled: "yes"
       ingressHost: "defi.dev.astranet.services"
       replicas: "1"
       servicePort: "3000"
       buildArgs: |-
        NEXT_PUBLIC_CHAIN_ID=11115
        NEXT_PUBLIC_NODE_1=https://rpc.astranaut.dev
        NEXT_PUBLIC_NODE_2=https://rpc.astranaut.dev
        NEXT_PUBLIC_NODE_3=https://rpc.astranaut.dev
        NEXT_PUBLIC_NODE_PRODUCTION=https://rpc.astranaut.dev
        NEXT_PUBLIC_HOST=https://defi.astranaut.dev
        NEXT_PUBLIC_EXPLORER=http://explorer.astranaut.dev
        NEXT_PUBLIC_GA_MEASUREMENT_ID=''
        NEXT_PUBLIC_FEE=100
        NEXT_PUBLIC_TITLE=SolarSwap
        NEXT_PUBLIC_WALLET_CONNECT_RELAY=relay.walletconnect.com
        NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID=af3dd8c81db591806b87e9dbdd42d670
        NEXT_PUBLIC_SENTRY_DSN=https://3440367258bb4aa39f6798ce548c98c8@sentry.astranet.live/5
        NEXT_PUBLIC_SENTRY_ENVIRONMENT=testnet
        NEXT_PUBLIC_DEFAULT_OUTPUT_CURRENCY=0x2039A56173fDac411975Bce6F756059Ac33d0d79
        NEXT_PUBLIC_GN_INFO_CLIENT=https://graph-node.astranaut.dev/subgraphs/name/solarswap/exchange-v1
        NEXT_PUBLIC_GN_BLOCK_CLIENT=https://graph-node.astranaut.dev/subgraphs/name/solarswap/blocks-v1
