name: Lint

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    unit-tests:
        runs-on: [self-hosted, linux]

        strategy:
            fail-fast: true
            matrix:
                node: [16]

        name: Lint

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@astraprotocol'
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: |
                npm install -g yarn
                echo yarn-cache-dir="$(yarn cache dir)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v2
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.yarn-cache-dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Setup npm token
              run: npm config set '//npm.pkg.github.com/:_authToken' "${{secrets.GITHUB_TOKEN}}"

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Run lint
              run: yarn lint
