name: 'Lint PR Title'

on:
    pull_request_target:
        types:
            - opened
            - edited
            - synchronize

jobs:
    main:
        name: Validate PR title
        runs-on: [self-hosted, linux]
        steps:
            - uses: amannn/action-semantic-pull-request@v4
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
