name: Production deployment
on:
  push:
    branches: ['main']        #
 
jobs:
  build-and-deploy:
     uses: AstraProtocol/github-actions-workflows/.github/workflows/stella-deployment-advanced.yml@main
     secrets:
       secretBuildArgs: |
         SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
         GITHUB_TOKEN=${{ secrets.GH_AUTH_TOKEN }}
     with:
       namespace: "solarswap-prod"
       ingressEnabled: "yes"
       ingressHost: "defi.prod.astranet.services"
       replicas: "1"
       servicePort: "3000"
       buildArgs: |-
        NEXT_PUBLIC_CHAIN_ID=11110
        NEXT_PUBLIC_NODE_1=https://rpc.astranaut.io
        NEXT_PUBLIC_NODE_2=https://rpc.astranaut.io
        NEXT_PUBLIC_NODE_3=https://rpc.astranaut.io
        NEXT_PUBLIC_NODE_PRODUCTION=https://rpc.astranaut.io
        NEXT_PUBLIC_HOST=https://solarswap.io
        NEXT_PUBLIC_EXPLORER=http://explorer.astranaut.io
        NEXT_PUBLIC_GTAG=G-MK9VVY7GT5
        NEXT_PUBLIC_FEE=100
        NEXT_PUBLIC_TITLE=SolarSwap
        NEXT_PUBLIC_WALLET_CONNECT_RELAY=wc-relay.astranaut.io
        NEXT_PUBLIC_SENTRY_DSN=https://3440367258bb4aa39f6798ce548c98c8@sentry.astranet.live/5
        NEXT_PUBLIC_SENTRY_ENVIRONMENT=mainnet
        NEXT_PUBLIC_DEFAULT_OUTPUT_CURRENCY=0x2039A56173fDac411975Bce6F756059Ac33d0d79
        NEXT_PUBLIC_GN_INFO_CLIENT=https://graph-node.astranaut.io/subgraphs/name/solarswap/exchange-v1
        NEXT_PUBLIC_GN_BLOCK_CLIENT=https://graph-node.astranaut.io/subgraphs/name/solarswap/blocks-v1
